### ISSUE TITLE
some problems with correct informations

### ISSUE THREAD

**Issue by Drazzild** [AntonyLeons/Ward#14]
hello i rented a vserver and wanted to use this tool but.. it gives me wrong informations....
![image](https://user-images.githubusercontent.com/20676504/160915601-2d65d529-403e-40ea-9e2d-61d8c4ae37ed.png)

the server got
4x AMD EPYC 7452 32-Core Processor, 2000 MHz
8gb of unkown ram so i think the 64bit is okay-ish but i think it should be DDR4 according to amds spec website of the CPU
and 300gb of space...
(edit) also Debian 10 buster not 11 O.o
 i rented this server from https://www.strato.de/

(edit) i can send you a full hwinfo log if needed

**Comment by AntonyLeons** [comment]
are you running in docker or the jar file? and yeah send hwinfo log.

**Comment by Drazzild** [comment]
i run the jar file with "screen -AmdS srvmon java -jar ward.jar"
its a vserver from strato and they are using virtuozzo to do that
here the log file:
[hwinfo.log](https://github.com/AntonyLeons/Ward/files/8420919/hwinfo.log)
and here a screenshot of the server config i rented from there 
![image](https://user-images.githubusercontent.com/20676504/161825328-e5e2c1ee-de9b-45ef-8dd3-85d75959bacb.png)

**Comment by AntonyLeons** [comment]
please try the new build and maybe run under sudo?
