### ISSUE TITLE
Unable to load in iFrame

### ISSUE THREAD

**Issue by Chocolate-Banana** [AntonyLeons/Ward#4]
I'm using organizr (https://organizr.app/) which launches websites in iFrames.

I wanted to use this as my landing page but it doesn't seem to load. Looking in the console, i'm getting jquery errors.

Any help would be greatly appreciated!

**Comment by AntonyLeons** [comment]
I cannot replicate this, post the error and your config

![image](https://user-images.githubusercontent.com/24696933/157448416-e7670689-ddfe-4058-8c6f-53f394427089.png)

**Comment by Chocolate-Banana** [comment]
Hi

It's working fine now, I kept getting errors in the console. Thanks for responding! 

![image](https://user-images.githubusercontent.com/43570997/157461485-63113bee-ab47-4b5b-aada-2abc174adfab.png)
