### ISSUE TITLE
Stats don't show, everything is at 0%

### ISSUE THREAD

**Issue by zetlex** [AntonyLeons/Ward#51]
What it looks like: ![image](https://user-images.githubusercontent.com/82660728/211162885-74321e8f-b3db-4778-903a-46750bd479e8.png)

I'm running in a docker container.

Docker Log: https://pastebin.com/ByxGi1Jc

I'm running some custom Ubuntu Server 22.04 OS from Orange Pi and it's running on an Orange-Pi ( off-brand Raspberry Pi )

The old version of Ward was working on the same setup.

Docker command:

sudo docker run --restart unless-stopped -it -d --name ward -p 4000:4000 -e WARD_PORT=4000 -e WARD_THEME=light --privileged antonyleons/ward

**Comment by zetlex** [comment]
Okay, so one of my chrome extensions are interfering with the panel which caused the status to show 0.

**Comment by AntonyLeons** [comment]
mad
