### ISSUE TITLE
CPU usage percent is not real

### ISSUE THREAD

**Issue by TEKNODEV2** [AntonyLeons/Ward#88]
![Screenshot (81)](https://github.com/AntonyLeons/Ward/assets/86974717/25753ac9-2472-4cc6-9742-03d7fc22c53d)
![Screenshot (82)](https://github.com/AntonyLeons/Ward/assets/86974717/24d639e0-3c1e-4198-972d-17818e1ca281)

the % on the windows task manager is not equal to ward cpu usage %
the RAM Usage is correct
the disk usage is correct.....but i have two disks...so how to decide which disk read?

**Comment by Anjiurine** [comment]
> ![Screenshot (81)](https://private-user-images.githubusercontent.com/86974717/275329015-25753ac9-2472-4cc6-9742-03d7fc22c53d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDEyMDgsIm5iZiI6MTcwNzkwMDkwOCwicGF0aCI6Ii84Njk3NDcxNy8yNzUzMjkwMTUtMjU3NTNhYzktMjQ3Mi00Y2M2LTk3NDItMDNkN2ZjMjJjNTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA4NTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4M2MwNjE4MGQ5YTUyM2Y2NTZlODY1NTBhYWQ3NDM2NTZlZWM4NmRhZDEwNWQ1ZDk1ZjNhZGUyM2Y2Yzg5OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUTgxDjixgDRU0yBuOrLS17uTVUdmyn9HEKb1kQKPCs) ![Screenshot (82)](https://private-user-images.githubusercontent.com/86974717/275329018-24d639e0-3c1e-4198-972d-17818e1ca281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDEyMDgsIm5iZiI6MTcwNzkwMDkwOCwicGF0aCI6Ii84Njk3NDcxNy8yNzUzMjkwMTgtMjRkNjM5ZTAtM2MxZS00MTk4LTk3MmQtMTc4MThlMWNhMjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA4NTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2M2UxNGI4MGM2NTA2YjAzN2Q4YmFhNjkyN2U2MDJlYjgyNWY4MzkzYzZhNzg4NWQ2MThmNDNlN2FhMDllOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0fEfALwHIOj9cIq2-jHIGttCVC67kDZQaHTB7hx1iu0)
> 
> Windows 任务管理器上的 % 不等于 ward cpu 使用率 % RAM 使用率正确，磁盘使用率正确.....但是我有两个磁盘......那么如何决定读取哪个磁盘呢？

This is due to the latest version of oshi, attempting to lower the version of oshi

**Comment by AntonyLeons** [comment]
there are many ways to calculate cpu usage, we use cpu ticks from oshi
disk is the combined value from all drives
